# Generated by Django 5.1.3 on 2025-05-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.SmallAutoField(primary_key=True, serialize=False),
        ),
    ]
