# Generated by Django 5.1.3 on 2025-05-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_duration',
            field=models.IntegerField(),
        ),
    ]
