# Generated by Django 5.1.3 on 2025-05-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_time_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time_duration_unit',
            field=models.CharField(choices=[('hours', 'ساعات'), ('days', 'أيام'), ('weeks', 'أسابيع')], default='days', max_length=20),
        ),
    ]
